{
 "title": "Single Tracelet Details",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "tracelet", "query": { "query": "label_values(device)" } }
  ]
 },
 "panels": [
  {
   "title": "Firmware Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fw{job=\"tracelet\", device=\"$tracelet\"}"
    }
   ]
  },
  { "title": "Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Wifi Strength",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "wifi_rssi_dbm{job=\"tracelet\", device=~\"$tracelet\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "wifi_ap{job=\"tracelet\", device=~\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected to Localization Server",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "lsi_is_connected{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Missing Acks from Localization Server",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "lsi_acks_missed{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connected to NTRIP Caster",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "ntrip_is_connected{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NTRIP Data Transfer",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(ntrip_transfer_bytes{job=\"tracelet\", device=\"$tracelet\"}[$__interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  { "title": "Fused", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Sensor Fusion State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sensor_fusion_state{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GNSS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Satellites in view",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "gnss_num_sats{job=\"tracelet\", device=~\"$tracelet\"}",
     "legendFormat": "{{system}}"
    },
    {
     "expr": "gnss_num_sv{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "sats_used"
    }
   ]
  },
  {
   "title": "GNSS Reference Station",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "ubx_ref_station_id{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sensor Fusion Status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "ubx_sensor_fusion_status_enum{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Programmable Gain Amplifier",
   "type": "timeseries",
   "description": "Shows gain of PGAs for each RF Block",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "gnss_pga{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{block}}"
    }
   ]
  },
  {
   "title": "Sensor Fusion Detail",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "ubx_sensor_fusion_detail{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Boot Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "ubx_boot_type_enum{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fix Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "gnss_fix_type_enum{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Runtime (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "ubx_runtime{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "gnss_eph_meters{job=\"tracelet\", device=\"$tracelet\"} < 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "gnss_heading_vehicle{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "vehicle"
    },
    {
     "expr": "gnss_heading_motion{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "motion"
    },
    {
     "expr": "gnss_heading_valid{job=\"tracelet\", device=\"$tracelet\"} * 100",
     "legendFormat": "valid"
    }
   ]
  },
  { "title": "UWB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Fix Type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "uwb_fix_type_enum{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "X-Position (m)",
   "type": "timeseries",
   "description": "UWB X position (m)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "uwb_x_meters{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "uwb_is_valid{job=\"tracelet\", device=\"$tracelet\"} * 10",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Horizontal position error (m)",
   "type": "timeseries",
   "description": "UWB estimated horizontal position error (m)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "uwb_eph_meters{job=\"tracelet\", device=\"$tracelet\"} < 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Y-Position (m)",
   "type": "timeseries",
   "description": "UWB Y position (m)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "uwb_y_meters{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Satlets in view",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "uwb_num_sats{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "uwb_head_vehicle{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "vehicle"
    },
    {
     "expr": "uwb_head_motion{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "motion"
    },
    {
     "expr": "uwb_head_valid{job=\"tracelet\", device=\"$tracelet\"} * 100",
     "legendFormat": "valid"
    }
   ]
  },
  {
   "title": "Satlets in view - addresses",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "uwb_sat{job=\"tracelet\", device=\"$tracelet\", type=~\".*_addr\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Satlets in view - addresses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uwb_sat{job=\"tracelet\", device=\"$tracelet\", type=~\".*_addr\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "UWB Tacho Speed",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "expr": "uwb_tacho_speed{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Satlets in view - RSSI",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "uwb_sat{job=\"tracelet\", device=\"$tracelet\", type=~\".*_rssi\"} < 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Position validity",
   "type": "timeseries",
   "description": "UWB position is valid (True/False)",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "uwb_is_valid{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Satlets in view - Non Line of Sight",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "uwb_sat{job=\"tracelet\", device=\"$tracelet\", type=~\".*_nlos\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Tacho", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Vehicle Speed (m/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "speed_meters_per_second{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Milage (m)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 104 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mileage_mm{job=\"tracelet\", device=\"$tracelet\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "System time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_time_seconds{job=\"tracelet\", device=\"$tracelet\"}*1000",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "SNTP Update",
   "type": "barchart",
   "description": "Should be around 1 per hour",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 113 },
   "targets": [
    {
     "expr": "changes(sntp_updates{job=\"tracelet\", device=\"$tracelet\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Time Change Rate",
   "type": "timeseries",
   "description": "Should be around 1",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 119 },
   "targets": [
    {
     "expr": "rate(system_time_seconds{job=\"tracelet\", device=\"$tracelet\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "GNSS UART Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 119 },
   "targets": [
    {
     "expr": "gnss_uart_errors{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "health{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "ESP Uptime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 125 },
   "targets": [
    {
     "expr": "uptime_seconds{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Free Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "free_heap_bytes{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reset Counters",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 133 },
   "targets": [
    {
     "expr": "reset_count{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "UBX IMU Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 139 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ubx_temperature_degrees{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu_load_percent{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Ignition",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "ignition_state{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Power cut",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_power_cut_unix_seconds{job=\"tracelet\", device=\"$tracelet\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sleep Manager State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 147 },
   "targets": [
    {
     "expr": "sleep_manager_state{job=\"tracelet\", device=\"$tracelet\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}